### ISSUE TITLE
Define array collums by fieldname so that additonal (custom) fields can be added to the array

### ISSUE THREAD

**Issue by joostveerman** [open-education-api/specification#19]
Currently arrays are defined as a single column.
For example in the v2 courseResult.yaml

    11  testResults:
    12    type: array
    13    description: The ids of testresults of the tests made by the student for this course
    14    items:
    15      type: string

By adding fieldname(s) to the array it becomes possible to add (custom) fields to the array without impact to current implementations.

    11  testResults:
    12    type: array
    13    description: The ids of testresults of the tests made by the student for this course
    14    items:
    15      testId: 
    16         type: string
    17      hu_testTitle:
    18        type: string

I propose to handle all arrays this way in the v2 specification of the OOA.

**Comment by joostfarla** [comment]
This is almost the same issue as https://github.com/open-education-api/specification/issues/9. The solution mentioned above will not work because the `items` property expects an Items Object, see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#itemsObject.

So, it would become something like:

```json
testResults:
  type: array
  items:
    type: object
    required:
      - testId
      - hu_testTitle
    properties:
      testId:
        type: string
      hu_testTitle:
        type: string
```

We will be discussing this further in https://github.com/open-education-api/specification/issues/9.
