### ISSUE TITLE
[Change request]: Some fields contain the wrong language

### ISSUE THREAD

**Issue by Tomeriko96** [open-education-api/specification#291]
### Organization

Vrije Universiteit Amsterdam

### Short description

Some fields contains values written in the wrong language, e.g. some fields with EN: translation have a dutch entry; and some NL: vertaling fields contain values written in english.

### Version

v5

**Comment by jelmerderonde** [comment]
@Tomeriko96 do you have some examples? Do you mean actual attributes in the objects or is the error in descriptions and examples?

**Comment by Tomeriko96** [comment]
@jelmerderonde

The issue was on values not matching the language tag is was associated with. See the example below. I had expected that there would be two different values, one in Dutch and one in English.


I also provide the code in R to reproduce it. 

Note: this is just a single example.


```
api_response <- httr::GET("https://demo05.test.surfeduhub.nl/education-specifications?pageSize=100")


jsonResponseText <- httr::content(api_response, as = "text", encoding = "UTF-8")

df <- jsonlite::fromJSON(jsonResponseText, flatten = TRUE) %>% 
  as.data.frame(check.names = FALSE) 

head(df$items.learningOutcomes, 1)
[[1]]
[[1]][[1]]
  language                                                                              value
1    en-GB EN TRANSLATION: nieuwe inzichten over het opdoen van kennis in een complexe wereld
2    nl-NL   NL VERTALING: nieuwe inzichten over het opdoen van kennis in een complexe wereld

[[1]][[2]]
  language                                                                 value
1    en-GB EN TRANSLATION: inzicht in de bijzondere eigenschappen van materialen
2    nl-NL   NL VERTALING: inzicht in de bijzondere eigenschappen van materialen
```

**Comment by jelmerderonde** [comment]
Hi @Tomeriko96 , you're looking at data from our "demo data" endpoints, which do not represent real Educational Institutions. These endpoints are not meant to have 100% realistic information. They mainly serve as an example and it would be too much work to make them 100% correct.

You can expect a "real endpoint" from an actual institution to have more realistic data where the languages match.

Since this is not an issue with the specification I'm closing this issue.
